name: Publish Canary

on:
  push:
    branches:
      - main

jobs:
  publish-canary:
    name: Build & Publish for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            target: x86_64-unknown-linux-gnu
            args: ""
          - platform: windows
            target: x86_64-pc-windows-msvc
            args: "--target x86_64-pc-windows-msvc --runner cargo-xwin"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: |
          npm install -g pnpm
          pnpm install

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt update
          # librerías para Tauri en Linux
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          # NSIS + LLVM + LLD + clang para Windows cross‑compile
          sudo apt-get install -y nsis llvm lld clang

      - name: Prepare Windows cross‑compile
        if: matrix.platform == 'windows'
        run: |
          rustup target add x86_64-pc-windows-msvc
          cargo install --locked cargo-xwin

      - name: Build & Publish Canary
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          GITHUB_REPOSITORY: ModpackStore/ModpackStore-Releases
        with:
          tagName: canary
          releaseName: "Canary Build canary"
          releaseBody: "Automated canary build for testing"
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
          owner: ModpackStore
          repo: ModpackStore-Releases
