name: Build Canary Release

on:
  push:
    branches:
      - main

jobs:
  build-canary:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        with:
          includeUpdaterJson: true
          owner: ModpackStore
          repo: ModpackStore-Releases

      # Clean up existing canary release before creating a new one

      - name: Remove existing canary release and tag
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          gh release delete canary --repo ModpackStore/ModpackStore-Releases --cleanup-tag -y || echo "No existing release to delete"

      - name: Release Canary Build
        uses: softprops/action-gh-release@v2
        with:
          repository: ModpackStore/ModpackStore-Releases
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          tag_name: canary
          name: Canary Build
          body: Automated canary build for testing
          files: |
            src-tauri/target/release/bundle/**/*
            src-tauri/target/release/bundle/*.json
          fail_on_unmatched_files: false