name: Build Canary Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./src-tauri -> ./target

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          GITHUB_REPOSITORY: ModpackStore/ModpackStore-Releases
        with:
          tagName: canary
          releaseName: "Canary Build canary"
          releaseBody: "Automated canary build for testing"
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          owner: ModpackStore
          repo: ModpackStore-Releases

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle
            src-tauri/updater/latest.json
          retention-days: 1

  upload:
    name: Upload release artifacts
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          merge-multiple: true

      - name: Remove existing canary release and tag
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          gh release delete canary --repo ModpackStore/ModpackStore-Releases --cleanup-tag -y || echo "No existing release to delete"
        continue-on-error: true

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          repository: ModpackStore/ModpackStore-Releases
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          tag_name: canary
          name: Canary Build canary
          body: Automated canary build for testing
          files: |
            bundle/**/*  # ← viene del artifact
            latest.json
          fail_on_unmatched_files: false
